spring.datasource.url=jdbc:h2:file:./data/agrodb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080
# JSON body (профил слика како base64 data URL)
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

app.jwt-secret=change-this-secret-key-for-prod-change-this-secret-key
app.jwt-expiration-ms=86400000
